/*	Java Visitor Pattern

	Note: In this problem you must NOT generate any output on your own. Any such solution will be considered as being against the rules and its author will be disqualified. The output of your solution must be generated by the uneditable code provided for you in the solution template.

	An important concept in Object-Oriented Programming is the open/closed principle, which means writing code that is open to extension but closed to modification. In other words, new functionality should be added by writing an extension for the existing code rather than modifying it and potentially breaking other code that uses it. This challenge simulates a real-life problem where the open/closed principle can and should be applied.

	A Tree class implementing a rooted tree is provided in the editor. It has the following publicly available methods:

	getValue(): Returns the value stored in the node.
	getColor(): Returns the color of the node.
	getDepth(): Returns the depth of the node. Recall that the depth of a node is the number of edges between the node and the tree's root, so the tree's root has depth  and each descendant node's depth is equal to the depth of its parent node .
	In this challenge, we treat the internal implementation of the tree as being closed to modification, so we cannot directly modify it; however, as with real-world situations, the implementation is written in such a way that it allows external classes to extend and build upon its functionality. More specifically, it allows objects of the TreeVis class (a Visitor Design Pattern) to visit the tree and traverse the tree structure via the accept method.

	There are two parts to this challenge.

	Part I: Implement Three Different Visitors
	Each class has three methods you must write implementations for:

	getResult(): Return an integer denoting the , which is different for each class:

	The SumInLeavesVisitor implementation must return the sum of the values in the tree's leaves only.
	The ProductRedNodesVisitor implementation must return the product of values stored in all red nodes, including leaves, computed modulo . Note that the product of zero values is equal to .
	The FancyVisitor implementation must return the absolute difference between the sum of values stored in the tree's non-leaf nodes at even depth and the sum of values stored in the tree's green leaf nodes. Recall that zero is an even number.
	visitNode(TreeNode node): Implement the logic responsible for visiting the tree's non-leaf nodes such that the getResult method returns the correct  for the implementing class' visitor.

	visitLeaf(TreeLeaf leaf): Implement the logic responsible for visiting the tree's leaf nodes such that the getResult method returns the correct  for the implementing class' visitor.
	Part II: Read and Build the Tree
	Read the -node tree, where each node is numbered from  to . The tree is given as a list of node values (), a list of node colors (), and a list of edges. Construct this tree as an instance of the Tree class. The tree is always rooted at node number .

	Your implementations of the three visitor classes will be tested on the tree you built from the given input.

	Input Format

	The first line contains a single integer, , denoting the number of nodes in the tree. The second line contains  space-separated integers describing the respective values of . 
	The third line contains  space-separated binary integers describing the respective values of . Each  denotes the color of the  node, where  denotes red and  denotes green. 
	Each of the  subsequent lines contains two space-separated integers,  and , describing an edge between nodes and .

	Constraints

	It is guaranteed that the tree is rooted at node .
	Output Format

	Do not print anything to stdout, as this is handled by locked stub code in the editor. The three getResult() methods provided for you must return an integer denoting the  for that class' visitor (defined above). Note that the value returned by ProductRedNodesVisitor's getResult method must be computed modulo .	*/
	
import java.util.ArrayList;
import java.io.*;
import java.util.*;
import java.text.*;
import java.math.*;
import java.util.regex.*;

import java.util.ArrayList;
import java.util.Scanner;

enum Color {
    RED, GREEN
}

abstract class Tree {

    private int value;
    private Color color;
    private int depth;

    public Tree(int value, Color color, int depth) {
        this.value = value;
        this.color = color;
        this.depth = depth;
    }

    public int getValue() {
        return value;
    }

    public Color getColor() {
        return color;
    }

    public int getDepth() {
        return depth;
    }

    public abstract void accept(TreeVis visitor);
}

class TreeNode extends Tree {

    private ArrayList<Tree> children = new ArrayList<>();

    public TreeNode(int value, Color color, int depth) {
        super(value, color, depth);
    }

    public void accept(TreeVis visitor) {
        visitor.visitNode(this);

        for (Tree child : children) {
            child.accept(visitor);
        }
    }

    public void addChild(Tree child) {
        children.add(child);
    }
}

class TreeLeaf extends Tree {

    public TreeLeaf(int value, Color color, int depth) {
        super(value, color, depth);
    }

    public void accept(TreeVis visitor) {
        visitor.visitLeaf(this);
    }
}

abstract class TreeVis
{
    public abstract int getResult();
    public abstract void visitNode(TreeNode node);
    public abstract void visitLeaf(TreeLeaf leaf);

}

class SumInLeavesVisitor extends TreeVis {
    private int result = 0;
    
    public int getResult() {
        return result;
    }

    public void visitNode(TreeNode node) {
      	//we don't work with nodes here, only with leafs
    }

    public void visitLeaf(TreeLeaf leaf) {
      	result += leaf.getValue();
    }
}

class ProductOfRedNodesVisitor extends TreeVis {
    private long result = 1;
    private final int modulo = 1000000007;
    
    public int getResult() {
        return (int)result;
    }

    public void visitNode(TreeNode node) {
      	if (node.getColor() == Color.RED)
            result = (result * node.getValue()) % modulo;
    }

    public void visitLeaf(TreeLeaf leaf) {
      	if (leaf.getColor() == Color.RED)
            result = (result * leaf.getValue()) % modulo;
    }
}

class FancyVisitor extends TreeVis {
    private int nonLeafEvenDepthSum = 0;
    private int greenLeavesSum = 0;

    public int getResult() {
        return Math.abs(nonLeafEvenDepthSum - greenLeavesSum);
    }

    public void visitNode(TreeNode node) {
    	if (node.getDepth() % 2 == 0)
            nonLeafEvenDepthSum += node.getValue();
    }

    public void visitLeaf(TreeLeaf leaf) {
    	if (leaf.getColor() == Color.GREEN)
            greenLeavesSum += leaf.getValue();
    }
}

public class Solution {
    private static int[] values;
    private static Color[] colors;
    private static HashMap<Integer, HashSet<Integer>> map;
  
    public static Tree solve() {
        Scanner sc = new Scanner(System.in);
        int nodesNum = sc.nextInt();
        values = new int[nodesNum];
        colors = new Color[nodesNum];
        map = new HashMap(nodesNum);
        for (int i = 0; i < nodesNum; i++)
            values[i] = sc.nextInt();
        for (int i = 0; i < nodesNum; i++)
            colors[i] = (sc.nextInt() == 0) ? Color.RED : Color.GREEN;
        for (int i = 0; i < nodesNum - 1; i++) {
            int u = sc.nextInt();
            int v = sc.nextInt();
            HashSet<Integer> uNeighbours = map.get(u);
            if (uNeighbours == null) {
                uNeighbours = new HashSet<>();
                map.put(u, uNeighbours);
            }
            uNeighbours.add(v);
            HashSet<Integer> vNeighbours = map.get(v);
            if (vNeighbours == null) {
                vNeighbours = new HashSet<>();
                map.put(v, vNeighbours);
            }
            vNeighbours.add(u);
        }
        sc.close();
        if (nodesNum == 1)
            return new TreeLeaf(values[0], colors[0], 0);
        TreeNode root = new TreeNode(values[0], colors[0], 0);
        addChildren(root, 1);
        return root;
    }
    
    private static void addChildren(TreeNode parent, Integer parentNum) {
        for (Integer treeNum : map.get(parentNum)) {
            map.get(treeNum).remove(parentNum);
            HashSet<Integer> grandChild = map.get(treeNum);
            boolean childHasChild = !(grandChild == null || grandChild.isEmpty());
            Tree tree;
            if (childHasChild)
                tree = new TreeNode(values[treeNum - 1], colors[treeNum - 1], parent.getDepth() + 1);
            else
                tree = new TreeLeaf(values[treeNum - 1], colors[treeNum - 1], parent.getDepth() + 1);
            parent.addChild(tree);
            if (tree instanceof TreeNode)
                addChildren((TreeNode)tree, treeNum);
        }
    }
	

    public static void main(String[] args) {
      	Tree root = solve();
		SumInLeavesVisitor vis1 = new SumInLeavesVisitor();
      	ProductOfRedNodesVisitor vis2 = new ProductOfRedNodesVisitor();
      	FancyVisitor vis3 = new FancyVisitor();

      	root.accept(vis1);
      	root.accept(vis2);
      	root.accept(vis3);

      	int res1 = vis1.getResult();
      	int res2 = vis2.getResult();
      	int res3 = vis3.getResult();

      	System.out.println(res1);
     	System.out.println(res2);
    	System.out.println(res3);
	}
}